name: patient_app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  http: ^1.2.2
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
